version: '3.8'

services:
  naming-server:
    image: szalaigeri/naming-server:0.0.1-SNAPSHOT
    pull_policy: always
    ports:
      - "8761:8761"
    networks:
      - currency-network

  api-gateway:
    image: szalaigeri/api-gateway:0.0.1-SNAPSHOT
    pull_policy: always
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://naming-server:8761/eureka
      - ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - currency-network
    restart: on-failure

  exchange-service:
    image: szalaigeri/currency-exchange-service:0.0.1-SNAPSHOT
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://naming-server:8761/eureka
      - ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - currency-network
    restart: on-failure

  conversion-service:
    image: szalaigeri/currency-conversion-service:0.0.1-SNAPSHOT
    pull_policy: always
    ports:
      - "8100:8100"
    environment:
      - EUREKA_CLIENT_SERVICE_URL=http://naming-server:8761/eureka
      - ZIPKIN_URL=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - currency-network
    restart: on-failure

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: on-failure

networks:
  currency-network: